kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-1
  spec:
    capacity:
      storage: 10240Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /opt/redis/redis-1
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-2
  spec:
    capacity:
      storage: 10240Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /opt/redis/redis-2
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-3
  spec:
    capacity:
      storage: 10240Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /opt/redis/redis-3
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-4
  spec:
    capacity:
      storage: 10240Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /opt/redis/redis-4
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-5
  spec:
    capacity:
      storage: 10240Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /opt/redis/redis-5
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: redis-6
  spec:
    capacity:
      storage: 10240Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /opt/redis/redis-6
