apiVersion: v1
kind: Service
metadata:
  name: redis-access-service
  namespace: redis-cluster
spec:
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: cluster
      port: 16379
      targetPort: 16379
  selector:
    app: redis
