apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service
  namespace: redis-cluster
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis-port
      port: 6379
    - name: redis-cluster-port
      port: 16379
