---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: sys
spec:
  type: ClusterIP
  clusterIP: 10.96.100.106
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  selector:
    app: redis-cluster

---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service
  namespace: sys
spec:
  clusterIP: None
  selector:
    app: redis-cluster
  ports:
   - port: 6379
     name: client
   - port: 16379
     name: gossip
