apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service
  namespace: sys
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis-cluster
  ports:
    - port: 6379
      name: client
    - port: 16379
      name: gossip
